version: '3' 
services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file: 
      - ".env"
    depends_on: 
      - redis
          
  celery:
      build: .
      restart: always
      command: celery -A gestorc beat -l info
      volumes: 
        - .:/src
      ports:
        - "5555:5555"
      env_file: 
        - ".env"
      depends_on:
        - web
        - redis

  redis:
      image: "redis:alpine"
      command: redis-server
      ports: 
        - "6379:6379"
    
