# Generated by Django 4.0.6 on 2022-08-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.address', verbose_name='Endereço'),
        ),
    ]
