# Generated by Django 4.0.6 on 2022-08-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da fatura'),
        ),
    ]
