# Generated by Django 4.0.6 on 2022-08-16 19:08

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18, verbose_name='CPNJ do cliente'),
        ),
    ]
