# Generated by Django 4.0.6 on 2022-08-16 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Somente números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Somente números'), django.core.validators.MaxLengthValidator(8, message='Tamanho inválido'), django.core.validators.MinLengthValidator(8, message='Tamanho inválido')], verbose_name='CEP'),
        ),
    ]
