# Generated by Django 4.0.6 on 2022-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_address_number_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro'),
        ),
    ]
