# Generated by Django 4.0.6 on 2022-08-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_value',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7, verbose_name='Valor da fatura'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='invoice_frequency',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annually', 'Anual')], default='monthly', max_length=50, verbose_name='Frequência da cobrança'),
        ),
    ]
