# Generated by Django 4.0.6 on 2022-10-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='Data de fim do contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Data de início do contrato'),
        ),
    ]
